image: node:8.10.0

before_script:
  - npm install -g @angular/cli
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


stages:
  - build
  - deploy

build client:
  stage: build
  script:
    - cd client
    - yarn install --frozen-lockfile
    - ng build --prod
  artifacts:
    paths:
      - client/dist/

build server:
  stage: build
  script:
    - cd server
    - yarn install --frozen-lockfile
    - ./node_modules/.bin/tsc -p tsconfig-prod.json
    - cp package.json dist/server/package.json
    - cp src/config/default.json dist/server/src/config/default.json
  artifacts:
    paths:
      - server/dist/

deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh-add "$DEPLOY_PRIVATE_KEY"
    - ssh yoc@yoc.gg "curl --output client_artifacts.zip 'https://gitlab.com/adamk33n3r/newyoc/-/jobs/artifacts/$CI_COMMIT_REF_NAME/download?job=build%20client'"
    - ssh yoc@yoc.gg "curl --output server_artifacts.zip 'https://gitlab.com/adamk33n3r/newyoc/-/jobs/artifacts/$CI_COMMIT_REF_NAME/download?job=build%20server'"
    - ssh yoc@yoc.gg "mkdir _tmp"
    - ssh yoc@yoc.gg "unzip -d _tmp client_artifacts.zip"
    - ssh yoc@yoc.gg "unzip -d _tmp server_artifacts.zip"
    - ssh yoc@yoc.gg "cp local.json _tmp/server/dist/server/src/config/local.json"
    - ssh yoc@yoc.gg "cd _tmp/server/dist/server && npm install"
    - ssh yoc@yoc.gg "mv live _old && mv _tmp live"
    - ssh yoc@yoc.gg "sudo /bin/systemctl restart yoc"
    - ssh yoc@yoc.gg "rm -rf _tmp"
  when: manual
