#!/bin/bash

build_client() {
  pushd client
  ng build --prod
  popd
}

build_server() {
  pushd server
  tsc -p tsconfig-prod.json
  cp -r dist/* ~/projects/newyoc-dist/server/
  cp src/config/default.json ~/projects/newyoc-dist/server/server/src/config/
  cp package.json yarn.lock ~/projects/newyoc-dist/server/server/
  popd
}

# build_client
build_server
