name: Build Client

run-name: Build Client run by ${{ github.actor }}

on:
  push:
    branches:
      - release
    paths:
      - "client/**"
  pull_request:
    branches:
      - release
    paths:
      - "client/**"
  workflow_dispatch:
      
jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '8.10.0'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Angular
        run: yarn ng build --prod
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: client/dist

  deploy-client:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build-client
    concurrency: deploy-client
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: client-build
          path: client/dist
      - name: List files
        run: |
          ls -al
          ls -al client/dist
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rzvc -i"
          SOURCE: "client"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          TARGET: "_tmp_server"
          SCRIPT_BEFORE: |
            rm -rf _tmp_client
            mkdir _tmp_client
          SCRIPT_AFTER: |
            rm -rf _old_client
            mv live/client _old_client
            mv _tmp_client/client live/client
