name: Build Client

run-name: Build Client run by ${{ github.actor }}

on:
  push:
    branches:
      - release
    paths:
      - "client/**"
  pull_request:
    branches:
      - release
    paths:
      - "client/**"
  workflow_dispatch:
      
defaults:
  run:
    working-directory: client

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock

  build:

    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Angular
        run: yarn ng build --prod
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: client/dist

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: client-build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rzvc -i"
          SOURCE: "client/dist/"
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          TARGET: "_tmp"
          SCRIPT_BEFORE: |
            rm -rf _tmp
            mkdir _tmp
          SCRIPT_AFTER: |
            rm -rf _old_client
            mv live/client _old_client
            mv _tmp/client live/client
